// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnr4FdB-zKgm9Ex0uBSfByZlPYxMAYdgE',
    appId: '1:526403050844:web:33b73531bf4018b9a87599',
    messagingSenderId: '526403050844',
    projectId: 'carwash-b17c6',
    authDomain: 'carwash-b17c6.firebaseapp.com',
    storageBucket: 'carwash-b17c6.appspot.com',
    measurementId: 'G-E6GVRPYNZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpNSccuW037qcJbM_dR9syKqSK828kHpc',
    appId: '1:526403050844:android:bf39fabb3e718b45a87599',
    messagingSenderId: '526403050844',
    projectId: 'carwash-b17c6',
    storageBucket: 'carwash-b17c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnP3mfXAGzQ40gjBpSWcsW8r7Py7V5WLU',
    appId: '1:526403050844:ios:101bfdd74a2bcca8a87599',
    messagingSenderId: '526403050844',
    projectId: 'carwash-b17c6',
    storageBucket: 'carwash-b17c6.appspot.com',
    iosClientId: '526403050844-d0lhelpktjv1fjqccsirea5m9o92vk3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.carWashProj',
  );
}
